### PR TITLE
Hopefully fixing image links properly

### PR DESCRIPTION
**Pull request by apt105**

### CODE REVIEW

**Review by jfirwin — COMMENTED** [review]
Lets give it a try! I'm doing some debugging on a private branch too, so hopefully that will yield some results if this doesn't!

**Comment by jfirwin** [comment]
It worked! I don't know why renaming those files made a difference, but it did it!

**Comment by jfirwin** [comment]
So you'll probably hate me if I ever change it back to `assets/img`, right? 😂 I was thinking if we put spec sheets for the various radios, they will probably be in pdf form so `assets/pdf` might work well.

**Comment by apt105** [comment]
Now that we've worked out how to do it, I'm not too worried about where things live, it'll be an easy Ctrl+H to sort out the links. Trying to make sure we work out a proper structure for everything is probably a good idea to get right early on though. For instance, I wonder if it might be an idea to move all the android images into their own subfolder to keep it nice and organised, so that we don't end up with an img folder with 6000 images....

**Comment by jfirwin** [comment]
I think that isolating specific images is a great idea. Let's do that.

**Pull request merged**
