### PR TITLE
Add supported hardware and individual OS firmware flashing guides

### PR DESCRIPTION
**Pull request by apt105**

### CODE REVIEW

**Comment by apt105** [comment]
Apologies, this needs to the assets directory merging into the img directory. Still learning git...

**Comment by jfirwin** [comment]
You're fine! I changed it and it was a dumb change. I'm still learning git too. Lets make that fix and then I can pull this change in.

**Comment by apt105** [comment]
Ok, I think I've managed to move the files to img, at least that was a lot less painful than when I had a conflict to resolve the other day...

**Comment by jfirwin** [comment]
Haha that one was also my fault, this looks great. I'll merge it in!

**Pull request merged**
