### PR TITLE
Move supported hardware

### PR DESCRIPTION
**Pull request by jfirwin**
I moved the supported hardware section into the getting started section and fixed one of the images I noticed was missing a `.png` filename extension. I've been pushing to main so far, but I think I should be better about creating new branches and creating pull requests.

### CODE REVIEW

**Comment by jfirwin** [comment]
@apt105 could you review these changes for me and approve a pull request? Then I'll pull it in. Also, in the future, I'll approve your pull requests and you can be the one to merge them to master.

**Review by apt105 — APPROVED** [review]
These all look good, didn't realise I missed the extension, whoops!

**Comment by apt105** [comment]
I'm not sure I can approve a pull request as I don't have write access to the project. Though I may have completely the wrong end of the stick....

**Comment by apt105** [comment]
Ok, ok, I see what you mean about approving the request. Apologies for being thick, done a 12 hour day at work!

**Comment by jfirwin** [comment]
You are fine, this week and next I'm crazy busy too so I completely understand. I'll merge this in tonight when I get on the computer.

**Pull request merged**
